-- ============================================================================
-- ADVERTENCIA DE SEGURIDAD: SCRIPT DESTRUCTIVO EXCLUSIVO PARA DESARROLLO LOCAL
-- ============================================================================
-- Este script ejecuta sentencias DROP TABLE ... CASCADE para resetear el esquema
-- en entornos locales de prueba. 
-- ESTÁ ESTRICTAMENTE PROHIBIDO su uso en entornos de Staging, QA o Producción.
-- ============================================================================
DROP TABLE IF EXISTS SOLICITUD_INFORMACION CASCADE;
DROP TABLE IF EXISTS CHAT_MENSAJES CASCADE;
DROP TABLE IF EXISTS PROGRESO_LECCION CASCADE;
DROP TABLE IF EXISTS INSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS SUSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS DETALLE_ORDENES CASCADE;
DROP TABLE IF EXISTS ORDENES CASCADE;
DROP TABLE IF EXISTS LECCION CASCADE;
DROP TABLE IF EXISTS PROGRAMA CASCADE;
DROP TABLE IF EXISTS INSTRUCTOR CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;
