-- Reset de tablas en desarrollo local
DROP TABLE IF EXISTS SOLICITUD_INFORMACION CASCADE;
DROP TABLE IF EXISTS CHAT_MENSAJES CASCADE;
DROP TABLE IF EXISTS PROGRESO_LECCION CASCADE;
DROP TABLE IF EXISTS INSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS SUSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS DETALLE_ORDENES CASCADE;
DROP TABLE IF EXISTS ORDENES CASCADE;
DROP TABLE IF EXISTS LECCION CASCADE;
DROP TABLE IF EXISTS PROGRAMA CASCADE;
DROP TABLE IF EXISTS INSTRUCTOR CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;
