-- ============================================================================
-- SCRIPT DESTRUCTIVO EXCLUSIVO PARA DESARROLLO LOCAL
-- ============================================================================
DROP TABLE IF EXISTS HISTORIAL_CONSULTA CASCADE;
DROP TABLE IF EXISTS DOCUMENTO_CHUNK CASCADE;
DROP TABLE IF EXISTS DOCUMENTO CASCADE;
DROP TABLE IF EXISTS SOLICITUD_INFORMACION CASCADE;
DROP TABLE IF EXISTS COMPROBANTE_PAGO CASCADE;
DROP TABLE IF EXISTS DETALLE_ORDENES CASCADE;
DROP TABLE IF EXISTS ORDENES CASCADE;
DROP TABLE IF EXISTS PROGRAMA CASCADE;
DROP TABLE IF EXISTS USUARIO CASCADE;

-- Limpieza de tablas heredadas del LMS antiguo
DROP TABLE IF EXISTS PROGRESO_LECCION CASCADE;
DROP TABLE IF EXISTS ACTIVIDAD_BLOQUE CASCADE;
DROP TABLE IF EXISTS LECCION CASCADE;
DROP TABLE IF EXISTS MODULO CASCADE;
DROP TABLE IF EXISTS BLOQUE CASCADE;
DROP TABLE IF EXISTS INSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS SUSCRIPCIONES CASCADE;
DROP TABLE IF EXISTS INSTRUCTOR CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;
DROP TABLE IF EXISTS CHAT_MENSAJES CASCADE;
DROP TABLE IF EXISTS documento_chunks CASCADE;
