spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lysandri_db
    username: lysandri_admin
    password: lysandri_secret_2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
